multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: jaco_base_link
    child_frame_id: jaco_base_link
groups:
  - name: jaco_arm
    base_link: jaco_base_link
    tip_link: jaco_link_6
default_collision_operations:
  - object1: jaco_base_link
    object2: jaco_link_1
    operation: disable  # Adjacent in collision
  - object1: jaco_link_1
    object2: jaco_link_2
    operation: disable  # Adjacent in collision
  - object1: jaco_link_2
    object2: jaco_link_3
    operation: disable  # Adjacent in collision
  - object1: jaco_link_3
    object2: jaco_link_4
    operation: disable  # Adjacent in collision
  - object1: jaco_link_4
    object2: jaco_link_5
    operation: disable  # Adjacent in collision
  - object1: jaco_link_5
    object2: jaco_link_6
    operation: disable  # Adjacent in collision
  - object1: jaco_link_6
    object2: jaco_finger_link_1
    operation: disable  # Adjacent in collision
  - object1: jaco_link_6
    object2: jaco_finger_link_2
    operation: disable  # Adjacent in collision
  - object1: jaco_link_6
    object2: jaco_finger_link_3
    operation: disable  # Adjacent in collision
  - object1: jaco_finger_link_1
    object2: jaco_finger_link_2
    operation: disable  # Never in collision
  - object1: jaco_finger_link_2
    object2: jaco_finger_link_3
    operation: disable  # Never in collision
  - object1: jaco_finger_link_1
    object2: jaco_finger_link_3
    operation: disable  # Never in collision
  - object1: jaco_finger_link_1
    object2: jaco_link_3
    operation: disable  # Never in collision
  - object1: jaco_finger_link_1
    object2: jaco_link_4
    operation: disable  # Never in collision
  - object1: jaco_finger_link_1
    object2: jaco_link_5
    operation: disable  # Never in collision
  - object1: jaco_finger_link_2
    object2: jaco_link_3
    operation: disable  # Never in collision
  - object1: jaco_finger_link_2
    object2: jaco_link_4
    operation: disable  # Never in collision
  - object1: jaco_finger_link_2
    object2: jaco_link_5
    operation: disable  # Never in collision
  - object1: jaco_finger_link_3
    object2: jaco_link_3
    operation: disable  # Never in collision
  - object1: jaco_finger_link_3
    object2: jaco_link_4
    operation: disable  # Never in collision
  - object1: jaco_finger_link_3
    object2: jaco_link_5
    operation: disable  # Never in collision
  - object1: jaco_link_1
    object2: jaco_link_3
    operation: disable  # Never in collision 
  - object1: jaco_link_3
    object2: jaco_link_6
    operation: disable  # Never in collision
  - object1: jaco_link_4
    object2: jaco_link_6
    operation: disable  # Never in collision
