joint_limits:
  jaco_joint_1:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  jaco_joint_2:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  jaco_joint_3:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  jaco_joint_4:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  jaco_joint_5:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  jaco_joint_6:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
